apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-adservice
spec:
  selector:
    matchLabels:
      app: eshop-adservice
  template:
    metadata:
      labels:
        app: eshop-adservice
    spec:
      containers:
        - name: eshop-adservice
          image: gcr.io/architect-certification-289902/01/eshop-adservice@sha256:59e7dbad7a5cebc6d72c4b649ed40e49e594e62f010389e8691386987a87e9ea
          ports:
          - containerPort: 8095
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/eshop_db"
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-adservice
spec:
  type: ClusterIP
  selector:
    app: eshop-adservice
  ports:
  - port: 8095